export const presets = {
    normal: {
        brightness: 100,
        contrast: 100,
        saturate: 100,
        hueRotation: 0,
        blur: 0,
        grayscale: 0,
        sepia: 0,
        opacity: 100,
        invert: 0,
    },

    drama: {
        brightness: 95,
        contrast: 140,
        saturate: 120,
        hueRotation: 0,
        blur: 0,
        grayscale: 0,
        sepia: 0,
        opacity: 100,
        invert: 0,
    },

    vintage: {
        brightness: 105,
        contrast: 90,
        saturate: 80,
        hueRotation: 0,
        blur: 0,
        grayscale: 10,
        sepia: 30,
        opacity: 100,
        invert: 0,
    },

    oldSchool: {
        brightness: 110,
        contrast: 85,
        saturate: 70,
        hueRotation: 10,
        blur: 1,
        grayscale: 20,
        sepia: 40,
        opacity: 100,
        invert: 0,
    },

    blackAndWhite: {
        brightness: 100,
        contrast: 130,
        saturate: 0,
        hueRotation: 0,
        blur: 0,
        grayscale: 100,
        sepia: 0,
        opacity: 100,
        invert: 0,
    },

    cinematic: {
        brightness: 95,
        contrast: 125,
        saturate: 110,
        hueRotation: -5,
        blur: 0,
        grayscale: 0,
        sepia: 10,
        opacity: 100,
        invert: 0,
    },

    warm: {
        brightness: 105,
        contrast: 100,
        saturate: 115,
        hueRotation: -10,
        blur: 0,
        grayscale: 0,
        sepia: 15,
        opacity: 100,
        invert: 0,
    },

    cool: {
        brightness: 100,
        contrast: 105,
        saturate: 110,
        hueRotation: 15,
        blur: 0,
        grayscale: 0,
        sepia: 0,
        opacity: 100,
        invert: 0,
    },

    faded: {
        brightness: 110,
        contrast: 80,
        saturate: 85,
        hueRotation: 0,
        blur: 0,
        grayscale: 5,
        sepia: 10,
        opacity: 100,
        invert: 0,
    },

    inverted: {
        brightness: 100,
        contrast: 100,
        saturate: 100,
        hueRotation: 0,
        blur: 0,
        grayscale: 0,
        sepia: 0,
        opacity: 100,
        invert: 100,
    },

    cyberpunk: {
        brightness: 105,
        contrast: 150,
        saturate: 160,
        hueRotation: 190,
        blur: 0,
        grayscale: 0,
        sepia: 0,
        opacity: 100,
        invert: 0,
    },

    retroPop: {
        brightness: 110,
        contrast: 120,
        saturate: 140,
        hueRotation: -25,
        blur: 0,
        grayscale: 0,
        sepia: 15,
        opacity: 100,
        invert: 0,
    }
};